**Importings**

In [3]:
import math 
import numpy as np
from scipy import spatial 
from scipy.spatial import distance
from numpy.random import seed
from numpy.random import randint
seed(1)

**1. (i) Finding Distance in 1D list from a point P using Euclidean**

In [30]:
# Lets consider five samples and consider a point P
S=[23,67,12,19,11]
P = [30]

In [6]:
euclidean=[]
for i in S:
  for j in P:
    euclidean.append(distance.euclidean(i,j))
Eucl=np.reshape(euclidean,(1,5))
print(Eucl)

[[ 7. 37. 18. 11. 19.]]


**(ii) Intra Points Distance calculation for  S=[23,67,12,19,11]**  **using** -
1. Euclidean 

In [31]:
euclidean=[]
for i in S:
  for j in S:
    euclidean.append(distance.euclidean(i,j))
Eucl=np.reshape(euclidean,(5,5))
print(Eucl)


[[ 0. 44. 11.  4. 12.]
 [44.  0. 55. 48. 56.]
 [11. 55.  0.  7.  1.]
 [ 4. 48.  7.  0.  8.]
 [12. 56.  1.  8.  0.]]


**Other Distance Metrics**


2.   Manhattan
3.   Cosine Similarity Distance






In [32]:
# Manhattan
manhattan=[]
for i in S:
  for j in S:
    manhattan.append(abs(i-j))
Manh=np.reshape(manhattan,(5,5))
print(Manh)

[[ 0 44 11  4 12]
 [44  0 55 48 56]
 [11 55  0  7  1]
 [ 4 48  7  0  8]
 [12 56  1  8  0]]


Cosine Similarity Distance 

In [33]:
cosine=[]
for i in S:
  for j in S:
    cosine.append(1-spatial.distance.cosine(i,j))
c=np.reshape(cosine,(5,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**(iii) Finding Euclidean Distance in 2D list from a point P1**

In [34]:
S1=[(23,47),(12,65),(11,87),(15,16),(32,50)]
P1=[(12,30)]

In [35]:
euclidean=[]
for i in S1:
  for j in P1:
    euclidean.append(distance.euclidean(i,j))
Eucl=np.reshape(euclidean,(5,1))
print(Eucl)

[[20.24845673]
 [35.        ]
 [57.00877125]
 [14.31782106]
 [28.28427125]]


**2. (i) Finding distance between two 1D arrays**






In [36]:
S1=[23,67,12,19,11]
S2=[101,150,280,90,75]

In [37]:
euclidean=[]
for i in S1:
  for j in S2:
    euclidean.append(distance.euclidean(i,j))
Eucl=np.reshape(euclidean,(5,5))
print(Eucl)

[[ 78. 127. 257.  67.  52.]
 [ 34.  83. 213.  23.   8.]
 [ 89. 138. 268.  78.  63.]
 [ 82. 131. 261.  71.  56.]
 [ 90. 139. 269.  79.  64.]]


**3. Finding the max and min elements from the Distance Matrix**

In [38]:
# Finding max element from the above matrix
max_value=np.max(Eucl)
print("Maximum Element from above matrix :-",max_value)

# Finding indices of the max element
result=np.where(Eucl==np.max(Eucl))
print('Tupple of arrays',result)
ListOfIndices=list(zip(result[0],result[1]))
for indices in ListOfIndices:
  print(indices)


Maximum Element from above matrix :- 269.0
Tupple of arrays (array([4]), array([2]))
(4, 2)


Initially all the indices are seperate clusters . In the above cell, based on maximum distance similarity we will be selecting the clusters. 
 With the help of indices we will be able to further cluster them. For example in the above cell (4,2) is again
 treated as one cluster 

In [39]:
# Finding min element from the above matrix
min_value=np.min(Eucl)
print("Minimum Element from above matrix :-",min_value)

# Finding indices of the min element
result=np.where(Eucl==np.min(Eucl))
print('Tupple of arrays',result)
ListOfIndices=list(zip(result[0],result[1]))
for indices in ListOfIndices:
  print(indices)

Minimum Element from above matrix :- 8.0
Tupple of arrays (array([1]), array([4]))
(1, 4)


Initially all the indices are seperate clusters . In the above cell, based on minimum distance similarity we will be selecting the clusters. 
 With the help of indices we will be able to further cluster them. For example in the above cell (1,4) is again
treated as one cluster.

**2. (ii) Finding Distance between two 2D arrays**

In [45]:
S3=[(55,90),(81,42),(17,82),(36,75),(43,88)]
S4=[(77,98),(49,70),(25,58),(29,117),(34,21)]

In [46]:
euclidean=[]
for i in S3:
  for j in S4:
    euclidean.append(distance.euclidean(i,j))
Eucl=np.reshape(euclidean,(5,5))
print(Eucl)

[[23.40939982 20.88061302 43.8634244  37.48332963 72.12489168]
 [56.14267539 42.52058325 58.24087911 91.26335519 51.4781507 ]
 [62.09669879 34.17601498 25.29822128 37.         63.3245608 ]
 [47.01063709 13.92838828 20.24845673 42.57933771 54.03702434]
 [35.44009029 18.97366596 34.98571137 32.20248438 67.60177512]]


**3. Finding the max and min elements from the Distance Matrix**

In [47]:
# Finding max element from the above matrix
max_value=np.max(Eucl)
print("Maximum Element from above matrix :-",max_value)

# Finding indices of the max element
result=np.where(Eucl==np.max(Eucl))
print('Tupple of arrays',result)
ListOfIndices=list(zip(result[0],result[1]))
for indices in ListOfIndices:
  print(indices)

Maximum Element from above matrix :- 91.2633551870629
Tupple of arrays (array([1]), array([3]))
(1, 3)


In [48]:
# Finding min element from the above matrix
min_value=np.min(Eucl)
print("Minimum Element from above matrix :-",min_value)

# Finding indices of the min element
result=np.where(Eucl==np.min(Eucl))
print('Tupple of arrays',result)
ListOfIndices=list(zip(result[0],result[1]))
for indices in ListOfIndices:
  print(indices)

Minimum Element from above matrix :- 13.92838827718412
Tupple of arrays (array([3]), array([1]))
(3, 1)


**2. (iii) Finding Distance between two arrays with 100 elements**

In [40]:
A1 = []
A2 = []
A1 = randint(200, 300, 100)
A2 = randint(500, 600, 100)

In [41]:
print(A1)
print(A2)

[237 212 272 209 275 205 279 264 216 201 276 271 206 225 250 220 218 284
 211 228 229 214 250 268 287 287 294 296 286 213 209 207 263 261 222 257
 201 200 260 281 208 288 213 247 272 230 271 203 270 221 249 257 203 268
 224 243 276 226 252 280 241 282 215 264 268 225 298 287 207 226 225 222
 209 267 223 227 237 257 283 238 208 232 234 210 223 215 287 225 271 292
 274 262 246 232 288 223 255 265 277 203]
[500 577 506 552 585 570 502 576 591 521 575 507 577 572 575 576 543 520
 530 536 507 545 568 557 582 596 513 510 523 581 507 524 574 592 520 532
 512 565 594 560 524 582 597 502 592 598 510 554 596 582 586 570 566 571
 548 554 515 505 517 542 520 548 522 513 597 553 584 510 596 555 561 556
 589 521 596 583 525 514 513 584 543 506 577 556 559 515 524 509 566 571
 553 569 536 521 540 577 591 549 547 577]


In [42]:
euclidean1 = []
for i in A1:
  for j in A2:
    euclidean1.append(distance.euclidean(i,j))
Eucl1 = np.reshape(euclidean1,(100,100))
print(Eucl1)

[[263. 340. 269. ... 312. 310. 340.]
 [288. 365. 294. ... 337. 335. 365.]
 [228. 305. 234. ... 277. 275. 305.]
 ...
 [235. 312. 241. ... 284. 282. 312.]
 [223. 300. 229. ... 272. 270. 300.]
 [297. 374. 303. ... 346. 344. 374.]]


**3. Finding the max and min elements from the Distance Matrix**

In [43]:
# Finding max element from the above matrix
max_value1 = np.max(Eucl1)
print("Maximum Element from above matrix :-", max_value1)

# Finding indices of the max element
result1 = np.where(Eucl1 == np.max(Eucl1))
print('Tupple of arrays', result1)
ListOfIndices1 = list(zip(result1[0],result1[1]))
for indices in ListOfIndices1:
  print(indices)

Maximum Element from above matrix :- 398.0
Tupple of arrays (array([37]), array([45]))
(37, 45)


Initially all the indices are seperate clusters. In the above cell, based on maximum distance similarity we will be selecting the clusters. 
With the help of indices we will be able to further cluster them. For example in the above cell, (54, 11) is again treated as one cluster 

In [44]:
# Finding min element from the above matrix
min_value1 = np.min(Eucl1)
print("Minimum Element from above matrix :-", min_value1)

# Finding indices of the max element
result2 = np.where(Eucl1 == np.min(Eucl1))
print('Tupple of arrays', result2)
ListOfIndices2 = list(zip(result2[0],result2[1]))
for indices in ListOfIndices2:
  print(indices)

Minimum Element from above matrix :- 202.0
Tupple of arrays (array([66]), array([0]))
(66, 0)


Initially all the indices are seperate clusters . In the above cell, based on minimum distance similarity we will be selecting the clusters. 
 With the help of indices we will be able to further cluster them. For example in the above cell, (28, 0) is again
treated as one cluster.